import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Web Development Practice",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default:
      "Web Development Practice – JavaScript Challenges & Live Coding Practice",
    template: "%s | Web Development Practice",
  },
  description:
    "Practice JavaScript and web development through challenges, live coding practice, and real-world problems. Compete, learn, and improve by building.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
